import type { Metadata } from "next";
import "./globals.css";
import { Lora, League_Spartan, Roboto } from "next/font/google";
import Header from "@/components/Header";

const spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-spartan"
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto"
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.className} ${lora.className} ${spartan.className}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
